#!/usr/bin/bash
##!/bin/bash
echo "***********************************************************"
echo "****************** gitt 1.3-02.2024 ***********************"
echo "***********************************************************"


for d in */ ; do

    echo "*-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-   $d"
    cd $d
    pwd
    git status
    git pull
    git add .
    git commit -m "committed $(date +%Y%m%d)"
    git push
    

    cd ..

done

git checkout

#/home/mr/blender-2.93.1-linux-x64/blender
#/home/m/İndirilenler/blender-2.93.1-linux-x64/blender
